### ISSUE TITLE
[feature/api_friend] : 마이탭 마시멜로우 연결 작업

### ISSUE THREAD

**Issue by SsongSik** [PomeTeam/POME_Android#16]
## Description
- 마이탭 마시멜로우 api 연결 작업

## To-do
- [ ] 마이탭 마시멜로우 분기처리
- [ ] 마시멜로우 레벨 분기처리
- [ ] 아이템데코레이션을 사용한 GridLayout 작성하기

## ETC
GridLayout의 item margin 확인
