### ISSUE TITLE
[feature/my_tab] 기존 뷰 코드 분석 및 mypage 뷰 수정 작업 진행

### ISSUE THREAD

**Issue by hanseul-Choi** [PomeTeam/POME_Android#21]
## Description
MyPage main view 코드 분석 및 변경 작업을 진행한다.
MyPageFragment 기능 작업도 진행한다.

## To-do
- [x] feature/api_friend merge 작업 진행
- [x] presentation/mypage 패키지 구조화 작업 진행 
- [x] fragment_mypage.xml 수정
- [x] MyPageFragment의 api 연결 작업 진행
- [x] viewModel 수정 작업 진행
- [x] DataBinding 작업 진행

**Comment by SsongSik** [comment]
고생하셨습니다!!
