### ISSUE TITLE
[feat/mypage_setting] MyPage Setting View 구현 작업

### ISSUE THREAD

**Issue by hanseul-Choi** [PomeTeam/POME_Android#28]
## Description
myPage의 Setting View 작업 수행

## To-do
- [x] 기존 Setting View 구현 코드 정리
- [x] Click 프레임 구현 처리 진행 
- [x] image api 연결하기
- [x] 친구 관리 페이지 랜딩
- [x] 문의 하기 페이지 랜딩
- [x] 알림 설정 주석처리
- [x] 신고 하기 페이지 랜딩
- [x] 약관 및 정책 페이지 랜딩
- [x] 오픈소스 라이센스 페이지 랜딩
- [x] 버전 정보 페이지 랜딩
- [x] 로그 아웃 기능 처리
- [x] 탈퇴하기 페이지 랜딩

**Comment by SsongSik** [comment]
고생하셨습니다!!
