### ISSUE TITLE
[feat/mypage_setting] 친구 관리 뷰 및 기능 구현

### ISSUE THREAD

**Issue by hanseul-Choi** [PomeTeam/POME_Android#29]
## Description
친구관리 뷰 및 기능 구현

## To-do
- [x] 친구 리스트 뷰 구현
- [x] 친구 리스트 가져오기 및 삭제 api 구현
- [x] 친구 삭제 다이얼로그 구현
